### ISSUE TITLE
Not realy a issue but...

### ISSUE THREAD

**Issue by SliverLIVE** [godotengine/godot-csharp-vscode#1]
Hi!
Is it possible to convert to Godot 3.2.1 or maybe 3.2.2?
I really need the "Node-Completion" and "Input-Completion" in VS Code!
This could make life so much easier... :)
Thx for the Plugin anyway.

**Comment by neikeq** [comment]
>Is it possible to convert to Godot 3.2.1

No, unfortunately this requires new changes introduced in 3.2.2 and 4.0dev.

>or maybe 3.2.2

Actually, yes. This will work with the next 3.2.2 release (I think it's not available in beta2 though).
The README is incorrect about 3.2.3 being the minimum version. I'll update it in the next release.
