### ISSUE TITLE
Add CoreCLR debugging support

### ISSUE THREAD

**Issue by yblainm** [godotengine/godot-csharp-vscode#15]
Hi!

First, I was having trouble using this extension because I was only using .NET Core. After lots of confusion, I did have the notion to install Mono (I'm on Ubuntu 20.04 and just used `apt` to get the necessary packages), since Mono Debug was listed as a dependency. No problems.

I may not fully understand how this is set up, but if I understand correctly, this extension uses the Mono Debug functionality to hook up to Godot, correct?

Would it be possible to extend this to a setup that only uses .NET? It seems like the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) supports .NET debugging. Does anyone know if this is only a matter of adding an extension setting plus some calls to methods defined by that extension?

Otherwise, debugging/play in editor/etc. don't work unless you have Mono. I thought Godot (I'm using 3.3.1) had .NET support, so I'm still unsure what the interplay is here between Godot, .NET, and Mono. Is it because Godot is using Mono in the runtime of a project, even if it's built using .NET CLI?

Once again, I'm not sure if I have an accurate portrayal of how this works, so this may not be applicable.

Thanks!

**Comment by neikeq** [comment]
I don't think it's possible because the mono [debugger libs](https://github.com/mono/debugger-libs) target .NET Framework.

**Comment by yblainm** [comment]
I'll take your word for it! :smile: If you have extra time, could you expand on what that means that they target .NET framework? I'm not clear on that. Do you mean installing Mono allows to debug .NET generally, and that's why we use it?

**Comment by neikeq** [comment]
The mono debugger libs which we use for debugging target `net472` aka .NET Framework 4.7.2, not .NET Core (.NET CLI cannot run .NET Framework programs). On Windows we can run it directly like any exe, but on Linux we need Mono.
