### ISSUE TITLE
executableArguments are being ignored

### ISSUE THREAD

**Issue by chaos-a** [godotengine/godot-csharp-vscode#19]
The following launch configuration should cause godot to immediately quit by passing the `-q` switch, however all of the executable arguments appear to be unused by this extension.
```"name": "Launch",
  "type": "godot-mono",
  "request": "launch",
  "mode": "executable",
  "executable": "${workspaceRoot}/Godot.exe",
  "executableArguments": [
      "--path",
      "${workspaceRoot}",
      "-q"
  ]
```

**Comment by raulsntos** [comment]
It seems the arguments passed to the executable are specified here:

https://github.com/godotengine/godot-csharp-vscode/blob/d6cb2f0c05f4bb17616c81d7934b5b6c77d00ebb/GodotDebugSession/GodotDebuggerSession.cs#L94

`GodotDebugSession` gets the `executable` argument but it doesn't look like it ever gets the `executableArguments` anywhere.

https://github.com/godotengine/godot-csharp-vscode/blob/d6cb2f0c05f4bb17616c81d7934b5b6c77d00ebb/GodotDebugSession/GodotDebugSession.cs#L87
