### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot-csharp-vscode#2]
Thank you for creating this.  I installed the extension but it doesn't have the "Play In Editor" option as well as code completion.  Do I need to manually configure this?

**Comment by akien-mga** [comment]
The extension needs Godot 3.2.3, which isn't released yet. Are you using a custom build from the `3.2` branch? Otherwise it won't work.

**Comment by neikeq** [comment]
To clarify, this extension for VSCode **does work** with 3.2.2. It's the Visual Studio extension that requires 3.2.3.

You have to create the debug configurations like this:

![Screenshot from 2020-07-03 19-20-33](https://user-images.githubusercontent.com/7718100/86488909-dc60d680-bd62-11ea-89df-feb4ff9dd0f2.png)

![Screenshot from 2020-07-03 19-21-08](https://user-images.githubusercontent.com/7718100/86488910-dcf96d00-bd62-11ea-8d2f-51a9a6f06c07.png)

It will generate the following. The `Play in Editor` option works out of the box. For the `Launch` you need to fix the path to point to the Godot Editor executable path you're using.

![Screenshot from 2020-07-03 19-22-17](https://user-images.githubusercontent.com/7718100/86488912-dd920380-bd62-11ea-8b3a-91689dc8e629.png)

**Comment by neikeq** [comment]
I suppose I should add this to the README.

**Comment by ondesic** [comment]
I'll try that.  Thank you.  Will this also allow the code completion to work?  Right now I can't get it to work

**Comment by ondesic** [comment]
It worked.  Thanks

**Comment by Torguen** [comment]
Thanks, that also worked for me.

**Comment by akien-mga** [comment]
> I suppose I should add this to the README.

Definitely. :)

I just set it up today myself, and without being familiar with VSCode, it's not a very straightforward process (though I figured it out eventually).

It should be in the README and in the Marketplace description (BTW, the README should also have a link to the Marketplace, the first question I asked myself was: how do I install this?).

**Comment by Torguen** [comment]
the worst thing is that you will have to do it in each project

**Comment by neikeq** [comment]
>(BTW, the README should also have a link to the Marketplace, the first question I asked myself was: how do I install this?).

I didn't know about this as the repo README is the marketplace description too, but I've just looked and it seems there are quite a few extension doing this so I guess it's fine.

**Comment by KevinTriplett** [comment]
I had this issue and the above worked -- @neikeq would you like me to send a PR for the README? (I notice this is pending since Sep)

**Comment by neikeq** [comment]
Yes, PRs welcome. Sorry I didn't have time for this.
