### ISSUE TITLE
Running from vscode doesn't work

### ISSUE THREAD

**Issue by tapir** [godotengine/godot-csharp-vscode#23]
`To configure a project for debugging open the Godot project folder in VS Code. Go to the Run tab and click on create a launch.json file. Select C# Godot from the dropdown menu. Now, when you start the debugger in VS Code your Godot project will run.`

This is from the official website however there is no option of "C# Godot" in launch.json options. Everything else works ok.

**Comment by raulsntos** [comment]
The `launch.json` options are context dependent, which means you will get different options based on which file is currently open and focused. Try following the [README.md](https://github.com/godotengine/godot-csharp-vscode#vscode-installation-and-configuration) steps without any file opened in VSCode.

PR #22 should fix the `package.json` configuration so the context dependent option shows up for C# files. It also adds a command to generate `launch.json` from the command palette (Ctrl + P) which may be useful.
