### ISSUE TITLE
New release to Marketplace?

### ISSUE THREAD

**Issue by sjml** [godotengine/godot-csharp-vscode#25]
Is there any roadmap for releasing a new version to the Visual Studio Marketplace? The version currently up there is more than a year old, and it would be good to incorporate some of the fixes that have happened since then.

**Comment by neikeq** [comment]
Sorry, I'm very busy currently. I will go through the remaining PRs in October and make a new version then.

**Comment by sjml** [comment]
Oh, no rush at all. Was just curious if current best practice was to install straight from the repo, or if another release was imminent. Take your time; I know there's a lot on the Godot plate right now. :)

**Comment by olestourko** [comment]
Any update on when this might happen?

**Comment by neikeq** [comment]
There are two pending PRs that I approved but need to be rebased. Once these PRs are merged I will make a new release.

**Comment by neikeq** [comment]
The new release (6623f6fac7fe7bf3ccbe3d3ce573ab8a67f97363) is now available on the marketplace.
