### ISSUE TITLE
"Play in Editor" hangs when Godot project is in subdirectory

### ISSUE THREAD

**Issue by olestourko** [godotengine/godot-csharp-vscode#26]
My project structure is a bit unusual:
```
project\
   .vscode\launch.json
   library_im_writing\
   godot_project\
```
With this configuration there doesn't appear to be a way of using the **Play in Editor** configuration. I've tried specifying the working directory in `launch.json` with `cwd` and symlinking my `project.godot` file to the root project directory. Neither appear to work. Godot doesn't even log any incoming debugger connection when running `godot -v`.

When I put a `.vscode\launch.json` inside my `godot_project` directory and open the folder in VSCode, that does work - so I don't think its my project settings causing this.

**Edit** Oddly enough, debugging seems to work just fine when I run the "Attach" configuration with my scene already running in Godot.

**Comment by raulsntos** [comment]
Each configuration is a separate implementation, `Attach` just attaches to the existing Godot process. The `PlayInEditor` configuration is implemented here:

https://github.com/godotengine/godot-csharp-vscode/blob/4785f95b60bf432452e53db36649bba840be2fe8/GodotDebugSession/GodotDebuggerSession.cs#L38-L74

It simply starts a debug session using the `GodotTools.IdeMessaging.Client` which is implemented in https://github.com/godotengine/godot/blob/master/modules/mono/editor/GodotTools/GodotTools.IdeMessaging/Client.cs

What this does is tries to connect to the Godot Editor on the IP `127.0.0.1` (or `localhost`). The `Client` constructor also takes a `godotProjectDir` parameter which it uses in order to read the metadata which is in`{godotProjectDir}/.godot/mono/metadata`. The metadata contains important data like the **port** which this extension needs to connect to the Godot Editor.

Anyway, the problem is the extension can't find this metadata because it can't find the `godotProjectDir`. This directory is actually assigned in this line:

https://github.com/godotengine/godot-csharp-vscode/blob/d6cb2f0c05f4bb17616c81d7934b5b6c77d00ebb/src/extension.ts#L140

As you can see, the directory is set to `folder.uri.fsPath` which is the root directory opened in VSCode which in your case is not the Godot project directory.

---

I believe the solution would be to create a new property for the `PlayInEditor` configuration that allows users to specify a custom `godotProjectDir` path to use instead of the root directory if specified.

**Comment by olestourko** [comment]
Thanks for the rundown. I want to take a shot at it locally - wow would I (generally) go about building this extension? Not familiar with `typescript` projects.

**Comment by raulsntos** [comment]
First you need to have [Node.JS](https://nodejs.org/) installed (the installer should add the `node` and the `npm` commands to your PATH). The last version should probably be fine, but this is what I'm using: `node v14.2.0 | npm 6.14.4`.

Now you have to download the dependencies of the project, just execute `npm install` in the root directory of the repository (where the `package.json` file is located).

You'll also need to install the `webpack` command globally: `npm install --global webpack-cli`.

Now you can build the extension using the `Makefile` with the `make build` command. This will transpile the typescript into javascript and compile the C# projects.

If it built successfully you can now launch the extension locally (the `Run Extension` configuration in `.vscode/launch.json`). This will open a new VSCode window with the locally-built extension installed, you can then open your godot project in this VSCode window and try it out.

**Comment by olestourko** [comment]
Got it built, thank you! The only extra thing I had to do was a `nuget restore` in the `**./GodotDebugSession/**` path before running `make build`. I'll see if I can get a project path config param added now and open up a PR if so.

**Comment by olestourko** [comment]
Do I need anything special to be able to debug the built extension? [These docs](https://code.visualstudio.com/api/get-started/your-first-extension) don't indicate so, but it doesn't register my breakpoints - maybe its something about webpack bundling everything together?

I have confirmed that the built extension runs in the new VSCode window though. Just trying to get either the debugger or some output going.

**Comment by olestourko** [comment]
Tried setting breakpoints in typescript and C# files; they disappear in the editor. `Console.WriteLine` also isn't producing any output in the host or debug VSCode instance :thinking: The built extension is being used though - as a test I raised an exception in the `GodotDebuggerSession.OnRun` method and it exits immediately when I run the launch config from the debug VSCode session.

**Comment by raulsntos** [comment]
You are right `Console.WriteLine` does not seem to output anything, sorry :upside_down_face:. There should be a log in `dist/GodotDebugSession/GodotDebugSession.log`. Use `Logger.Log` to write to it. From `typescript` you can use `console.log` and that will be written to the `DEBUG CONSOLE` tab in the host VSCode instance.

Also, the C# is only executed when a new debug session is started so when you run `PlayInEditor` from the debug VSCode instance.

And remember to run `make build` after making any changes or the source will go out of sync, that may be why the editor can't add breakpoints, not sure.

**Comment by olestourko** [comment]
Using `Logger.Log` in the C# worked for getting output. Also hardcoding my Godot project path got the debugger to connect to the Godot editor, so yay!

For some reason `console.log` calls in `.ts`  don't output in my host's debug console tab either, along with the unknown/unbound breakpoint problem - I wonder if there might be something up with VSCode here. Tried `make build` and `make build-debug` and no luck with either.

**Comment by raulsntos** [comment]
Yeah, that's weird. I don't know what could be the cause, but it does sound like it might be a VSCode issue. I'm using VSCode `1.58.2` in Ubuntu `21.04`.

**Comment by olestourko** [comment]
Mhm it gets even weirder - I can comment out entirely the activate/deactivate functions in `extension.ts`, rebuild, and it still works somehow. Even tried deleting the `dist` and `out` directories before rebuilding. `VScode 1.60.1` / `Ubuntu 20.04` here. I uninstalled the extension from the marketplace too. Smells like some kind of caching problem.

**Comment by raulsntos** [comment]
The extension should still compile fine without those methods and even launch the debug VSCode instance but running a launch configuration like `PlayInEditor` should fail (in my case it does nothing, not even showing an error).

**Comment by olestourko** [comment]
Still runs after adding that exception and rebuilding. Truly bizarre. I even commented out the comments of every file in the `src` directory and that didn't break it either!

**Comment by raulsntos** [comment]
Can you see the modified code in `dist/extension.bundled.js`?

**Comment by olestourko** [comment]
Yes, and checking the diff between the original `extension.bundled.js` and the one compiled after i added the exception and commented out the remainder of the `activate` method shows that it is indeed smaller.

**Comment by raulsntos** [comment]
It doesn't seem to be using it. Try executing the command `code --extensionDevelopmentPath=/path/to/godot-csharp-vscode` directly. The path should be the absolute path to the root of the repository, where the `package.json` file is located. The `code` command might not be in your PATH, in that case you can replace it with the absolute path (might be `/usr/bin/code` or `/bin/code`).

**Comment by olestourko** [comment]
I have no idea at this point -

Changed the contents of the bundle file to just `throw new Error('Hello World');`

`code --extensionDevelopmentPath=/home/oles/Documents/projects/godot-csharp-vscode` brings up VSCode as you'd expect and i can launch my project through the editor with the extension. No errors raised about the extension at all.
`code --extensionDevelopmentPath=/home/oles/Documents/projects/godot-csharp-vscode/dist` doesn't detect the extension when i attempt to launch it, as i'd expect, so it is reading the extension's `package.json` file.

**Comment by raulsntos** [comment]
I'm running out of ideas too. The error should be raised as soon as the VSCode window opens, no need to do anything else. The `package.json` file specifies `main` to be `./dist/extension.bundled.js` so it's weird if it uses some other file.

**Comment by olestourko** [comment]
This has to be some kind of VSCode caching issue. I _finally_ got it to raise an exception by just saving random characters to `extension.bundled.js`. That threw an exception! And now it seems to be picking up my changed to the bundle file.

**Comment by olestourko** [comment]
And debugger breakpoints are working not too. There are a lot of things in life that don't make senshe...

Anyways thanks a bunch for the help, much appreciated!

**Comment by raulsntos** [comment]
That was definitely unexpected, but I'm glad it works now :smile:

**Comment by olestourko** [comment]
I figured out what was going on. I had to update the extension's activation event to scan for `project.godot` **anywhere** in the project directory instead of just the root :slightly_smiling_face: 

```
	"activationEvents": [
		"workspaceContains:**/project.godot",
		"onDebugResolve:godot"
	],
```
I must've switched to my base Godot project when I was messing around with the `extension.bundled.js` file earlier, which is why it somehow appeared to just start working for some reasom

**Comment by raulsntos** [comment]
Ah, that makes sense. I just assumed it would look for the `project.godot` file in subdirectories too but I guess not.

**Comment by olestourko** [comment]
So i'm working on a PR to add this functionality now. Looks like the Godot project path setting will need to be exposed through a `contributes` setting and not a `launch.json` config setting, since the extension needs to know the location of `project.godot` right from activation:

https://github.com/godotengine/godot-csharp-vscode/blob/4785f95b60bf432452e53db36649bba840be2fe8/src/extension.ts#L97

**Comment by raulsntos** [comment]
Oh yeah, that's used for the Client that connects to the Godot Editor for the autocomplete.

If you are familiar with the C# extension, what it does is it finds all the C# projects and if there are multiple ones it prompts you to select one but then you can also change the selected project from the status bar. I think it that'd be the best way to implement this if you are up for it, what do you think?

**Comment by olestourko** [comment]
I got it working through a `contributes` setting, but agreed that a selector is a better way of doing it. I'll give it a shot - i mean i'm not familiar with writing extensions or even TS, but it can't be _that_ difficult to figure this out. The C# extension already has a good starting point: https://github.com/OmniSharp/omnisharp-vscode/blob/1756e252a74b051097ed9acb9e080fba8fdff185/src/main.ts#L102

**Comment by olestourko** [comment]
Found a dedicated example for doing this kind of stuff: https://github.com/microsoft/vscode-extension-samples/tree/main/statusbar-sample

It's a start
![Screenshot_2021-09-22_17-39-51](https://user-images.githubusercontent.com/3958783/134425798-88bfb94a-90c2-43c4-be58-b6b6a048dbba.png)

**Comment by olestourko** [comment]
Opened PR for this: https://github.com/godotengine/godot-csharp-vscode/pull/28

**Comment by neikeq** [comment]
Does #28 fix this issue?

**Comment by olestourko** [comment]
Yep, i'll close this issue now
