### ISSUE TITLE
Incompatible with recent VSC Version

### ISSUE THREAD

**Issue by eazrael** [godotengine/godot-csharp-vscode#29]
Win10 64bit / Godot_v3.3.4-stable_mono_win64 / VSC  1.60.2 / C# Tools for Godot 0.1.3 / .Net 5.0

Apparent Issue: No launch.json can be generated. When starting launch.json generation in debug pane, no "C# Godot" option is provided. Starting project in Godot works as long as "waiting for debugger" is disabled. When "waiting for debugger" is enabled, game will crash with a timeout. 

Steps to reproduce: 
- Use versions as above. 
- Start new project in godot
- Create scene with root node. Attach C# Script. VSC starts, project is generated. 
- Try to generate launch.json. Does not work

It seems that in package.json -> contributes->debuggers->"enableBreakpointsFor" is no longer supported as when the package.json is opened it will be flagged as not allowed
"Property enableBreakpointsFor is not allowed."   -> https://code.visualstudio.com/updates/v1_42

Maybe the cause or not. 
Seems that raulsntos Pull Request #22  also corrects this. 

Unfortunately I was not able to build the extension myself so I cannot test it that really fixes this problem :-(

**Comment by wenbingzhang** [comment]
I also encountered the same problem
