### ISSUE TITLE
Mac OS add support for Debug and System Output

### ISSUE THREAD

**Issue by LordBrkica** [godotengine/godot-csharp-vscode#31]
Hi,

I have been using Godot Mono + VScode on Windows 10 and there everything worked ok. 

I switched to Mac (intel cpu) and continued with Godot Mono + VScode combination.
But now I am missing some features:

- I don't output to console/terminal by default. This means I cannot see  _Debug.Writeline("mkjklj")_  anywhere. I can see _GD.Print("dfjhdkjh")_  in the Godot editor Output.
- There is a lot of "system" output (which I assume is in same category with _Debug.Writeline()_ . It would be of great help if one could see this text.

So I am asking would it be possible to add default ouput to terminal on MacOS.

**Comment by raulsntos** [comment]
Which launch configuration are you using? `Play In Editor`, `Launch` or `Attach`.

Have you tried `System.Console.WriteLine` and does that work?

I could not reproduce in Pop OS 21.04 with the `Launch` configuration, note that `Play In Editor` currently does not print any output (reported in #11).

**Comment by LordBrkica** [comment]
I am tried all 3 configurations.

#11 is a minor nuisance for me as GD.Print at least can be seen somewhere (the Godot Editor). 

In my case, output window is usually showing some omnisharp logs and terminal nothing.
![Screenshot 2021-11-09 at 15 28 06](https://user-images.githubusercontent.com/51578785/140942621-68cca8c9-2456-4448-a843-c5d0ba4dfeb2.png)

Like I said the problem is not so much in not seeing the _Debug.Writeline_ (or _System.Console.WriteLine_), its all the other system outputs that get outputed and are not seen anywhere.

**Comment by LordBrkica** [comment]
I dont see anything in my DebugConsole. But I can step with F10 and breakpoints in VSCode work.

This is my configuration:
```
        {
            "name": "Play in Editor",
            "type": "godot-mono",
            "mode": "playInEditor",
            "request": "launch",
            "port": 23685
        },
```

**Comment by raulsntos** [comment]
I'm using the `Launch` configuration, since `Play in Editor` won't show output.

```jsonc
{
	"name": "Launch",
	"type": "godot-mono",
	"request": "launch",
	"mode": "executable",
	"executable": "/usr/bin/godot", // This is the path to my godot editor binary
	"executableArguments": [
		"--path",
		"${workspaceRoot}"
	]
}
```

**Comment by LordBrkica** [comment]
I am a mac newb, I used `launch` but I havent edited the paths, (so it only started the editor but not the app).

I changed my launch to this:
```
        {
            "name": "LaunchTest3",
            "type": "godot-mono",
            "request": "launch",
            "mode": "executable",
            "executable": "/Applications/Godot_mono.app/Contents/MacOS/Godot", 
            "executableArguments": [
                "--path",
                "${workspaceRoot}"
            ]
        }
```
and now it works.

Thanks for your help !
