### ISSUE TITLE
Only attach works with Godot 4.0

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot-csharp-vscode#38]
**OS/device including version:**
Windows 10

**Issue description:**
You can attach to a running instance, but `Play in Editor`, `Launch`, and `Launch (Select Scene)`. Do not work.
Unexpectedly, `Launch` tries to build and run the current scene open in the editor, and crashes. I only noticed due to some `_Ready()` `GD.Print()` method calls printing from the current scene.

**Comment by raulsntos** [comment]
This extension was developed for Godot 3.x. It's likely that Godot 4.0's breaking changes made it incompatible with this extension and needs to be updated to support it.

I don't think it'd be very useful to start doing that work now since Godot 4.0 is still in alpha and the C# module is in the process of being ported to .NET 6.0.

**Comment by markdibarry** [comment]
All good points. If that's all there is to `Launch` and `Play in Editor` I'm confused why it'd try to run the currently open scene. `Attach` still works, so I thought there was a chance that maybe another launch mode wouldn't be that far off, so was worth reporting. Obviously no official mono builds are released, but there are always the few like me who do custom builds to still be able to contribute bug tickets and PRs. If a separate extension is planned, rather than to work on compatibility for this one, it'd probably be a quick solution then to update the ReadMe to mention that, so further 4.0 bugs can be closed.

**Comment by raulsntos** [comment]
Just want to clarify that it should be opening the main scene, not the currently open the scene.

There could be a number of things changed in 4.0 that broke the extension, off the top of my head I remember the `.mono` folder was moved to `.godot/mono` where we store a metadata file with the port that the extension needs to attach the debugger so maybe that's what's causing the issue.

**Comment by markdibarry** [comment]
You were absolutely right. I created `.mono/metadata` directories in my project root and a `ide_messaging_meta.txt` with the same port number as the other one and `Play in Editor` now works. I'll try the changes you provided above. Seems like a pretty easy extra step to get things going in 4.0

Thanks!

**Comment by markdibarry** [comment]
As the merge to .NET 6 has happened, this is irrelevant.
