### ISSUE TITLE
Specify .NET SDK version for Godot 3.5 newcomers

### ISSUE THREAD

**Issue by marcosdly** [godotengine/godot-csharp-vscode#50]
I'm a newcomer to Godot that has only built the games on the docs tutorial in GDScript, with that in mind, I'm asking you to specify that the correct SDK version in case we choose .NET is .NET Core 3.1, or provide a tutorial to set the correct version/output in the `.csproj` file.

As a beginner to Godot and the C# language, the first thing I did was research what is .NET and its versions, so I learned about .NET Core, .NET Framework, and Mono, but when accessing the .NET website I came across one single version: .NET 6. Doing a little bit more research I found out that Microsoft now also owns Mono and Xamarin, and that since .NET 5 all these implementations have been merged and are now part of a single SDK.

So I checked Godot's docs and there reads the following:

> Install the latest stable version of the [.NET SDK](https://dotnet.microsoft.com/download), previously known as the .NET Core SDK.
> 
> From Godot 3.2.3 onwards, installing Mono SDK is not a requirement anymore, except it is required if you are building the engine from source.

Fair enough. So I downloaded .NET 6 and ended up having some issues. The first one was outside Godot, but the second one had Godot not building the game. Some people online were constantly asking to select the `dotnet CLI` build tool, but mine was already selected. After a little bit more research, I simply uninstalled .NET 6 and installed .NET Core 3.1 from the "All .NET versions" link at the bottom of the main download link, and it just worked. That easy.

**Comment by marcosdly** [comment]
Wrong repo. I'm so so sorry :/

**Comment by raulsntos** [comment]
@marcosdly I don't know what issues you had but like the docs say, the version of the SDK you should install is the latest one (which is currently .NET 6).

I do not recommend using an older version of the SDK. Keep in mind the .NET Core 3.1 version will reach end of life by December 13, 2022 (see https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). The latest version of the SDK is able to compile projects that target older frameworks so there is no reason to stay in an older version of the SDK.

If you have further issues or questions you can use the dedicated community channels: https://godotengine.org/community
