### ISSUE TITLE
Unable to run a project using "Launch" option cause of "\r" in tasks.json

### ISSUE THREAD

**Issue by fhgaha** [godotengine/godot-csharp-vscode#51]
**OS/device including version:**
Windows 10

**Issue description:**
Unable to run a project using "Launch" option. "Play in Editor" works fine though. After pressing "Launch" in VS Code terminal displays
```
 *  Executing task: C:/ProgramsNoInstallRequired/Godot_v3.5-stable_mono_win32/Go --build-solutions --path D:\MyProjects\Godot Projects\Trains --no-window -q 


 *  The terminal process failed to launch: Path to shell executable "C:\ProgramsNoInstallRequired\Godot_v3.5-stable_mono_win32\Godo" does not exist. _win32.exe
```
There is workaround: in generated file `tasks.json` you should remove "\r" at the end of the path `"command": "<--Your path to godot.exe-->\r"`.

**Comment by fhgaha** [comment]
> * Can you share the generated `tasks.json`?

here:
```

{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build",
			"command": "C:/ProgramsNoInstallRequired/Godot_v3.5-stable_mono_win32/Godot_v3.5-stable_mono_win32.exe\r",
			"type": "process",
			"args": [
				"--build-solutions",
				"--path",
				"${workspaceRoot}",
				"--no-window",
				"-q"
			],
			"problemMatcher": "$msCompile"
		},
		{
			"label": "publish",
			"command": "dotnet",
			"type": "process",
			"args": [
				"publish",
				"${workspaceFolder}/Trains.csproj",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"problemMatcher": "$msCompile"
		},
		{
			"label": "watch",
			"command": "dotnet",
			"type": "process",
			"args": [
				"watch",
				"run",
				"--project",
				"${workspaceFolder}/Trains.csproj"
			],
			"problemMatcher": "$msCompile"
		}
	]
}

```


> * Do you have the godot binary in your `%PATH%`? If so, make sure the path in your environment variables is correct and valid.

Is that some kind of windows setting?

> * Was the Godot engine open when generating the `tasks.json` file? If so, try generating the `tasks.json` file with the Godot engine closed and see if it makes a difference.

I did that and instead of path there is `"command": "<insert-godot-executable-path-here>",`. The whole generated task.json:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build",
			"command": "<insert-godot-executable-path-here>",
			"type": "process",
			"args": [
				"--build-solutions",
				"--path",
				"${workspaceRoot}",
				"--no-window",
				"-q"
			],
			"problemMatcher": "$msCompile"
		}
	]
}
```

**Comment by raulsntos** [comment]
> Is that some kind of windows setting?

The `PATH` is an environment variable that contains the locations of executables so they can be found by name, some users add the path to the Godot engine binary there so they can more easily open it from a terminal. There is no need to use this, I just wanted to check if you were using it.

> It was. I generated the `tasks.json` file with the Godot engine closed and instead of path there is `"<insert-godot-executable-path-here>",`.

When the Godot engine is open the extension communicates with it to obtain the path to the binary to use in the `tasks.json` and `launch.json` files. This communication happens by using an `ide_messaging_meta.txt` file, the editor writes its metadata to that file so the extension can read it an obtain all the information it may need. When writing new lines, each operating system use different characters (Unix uses `\n` and Windows uses `\r\n`), we are currently splitting the lines by `\n` but in Windows that leaves a `\r` on each line which is causing this issue.

**Comment by fhgaha** [comment]
Informative! Thank you!
