### ISSUE TITLE
Full compatibility with Roslyn

### ISSUE THREAD

**Issue by cybernaut4** [godotengine/godot-csharp-vscode#57]
# Situation 

Visual Studio Code's C# extension just got a massive update from **1.26**.0 to **2.0**.320 ([see here](https://github.com/dotnet/vscode-csharp/commit/78b860378b8b41b04865d29e8fefb859320e75e0)), which replaces Omnisharp with Roslyn as the default language server. 

I can tell it has an amazing processing speed and is more current than OmniSharp.

# Problem

The current Godot plugin doesn't communicate with Roslyn about any existent, project-based SignalNames and MethodNames.

### Example
![image](https://github.com/godotengine/godot-csharp-vscode/assets/68290346/5d583ad6-ceda-484e-bd07-5a0cb8716673)

### Suggestions

* Add an option in the extension's settings to switch between OmniSharp and Roslyn, making Roslyn as the default.
* Any mentioning about overlooked details is appreciated.

**Comment by raulsntos** [comment]
There's no communication with Roslyn, the `SignalName` and `MethodName` classes are generated by [C# source generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) and unrelated to this extension. Roslyn generates these classes by invoking the generators as part of the compilation.

If VSCode's C# extension doesn't recognize them then it's a bug in their [extension](https://github.com/dotnet/vscode-csharp). Looks like this is the same issue or related to https://github.com/dotnet/vscode-csharp/issues/5999.

**Comment by jasonmalinowski** [comment]
Just chiming in here from the Roslyn team: we do expect generators to be running but we have had some reports of various generators not working with new extension. We are investigating those reports (https://github.com/dotnet/roslyn/issues/68590 is one bug, https://github.com/dotnet/vscode-csharp/issues/5999 is the other you pointed to). If you see those bugs get closed and your stuff is still not working, do file a bug and we'll take a look.

**Comment by geekley** [comment]
As a temporary workaround, you can tell C# extension to use Omnisharp instead of Roslyn with `"dotnet.server.useOmnisharp": true` in `settings.json` and get proper support to generated code.
Note that this setting seems to not be declared in the extension manifest, so it may appear to be unrecognized by VSCode, but it still works.

**Comment by geekley** [comment]
This likely won't solve the issue, but still, it's probably better just in case.
You might wanna add to the generated sources:
- `// <auto-generated/>` at the beginning
- [GeneratedCodeAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute?view=net-6.0)

For reference, you can see how .NET 7 [GeneratedRegexAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.generatedregexattribute?view=net-7.0) adds those to its generated code.

**Comment by raulsntos** [comment]
A file is considered generated by .NET[^1] if it has a `// <auto-generated />` comment as the first line of the file, or if the file name ends with one of these suffixes: `.designer`, `.generated`, `.g` or `.g.i`.

We use the `.generated` suffix for all our generated source code (see https://github.com/godotengine/godot/pull/67766) so that shouldn't be a problem.

[^1]: This is described in the Microsoft documentation for nullable references: https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references

**Comment by jasonmalinowski** [comment]
FYI we should have a fix on the way for this: https://github.com/dotnet/roslyn/pull/70331 (and yes, I'm embarrassed here.)

**Comment by jasonmalinowski** [comment]
And version 2.7.25 is now out to the VS Code extension marketplace, so that _should_ fix this. If there's still issues do let me know and we'll dig further!

**Comment by raulsntos** [comment]
Tested 2.7.25 and works great, so I'll close this issue as fixed. Thank you so much!

**Comment by ana-rchy** [comment]
still doesnt work with the newest version of the extension

**Comment by raulsntos** [comment]
@ana-rchy If you still have issues with the Microsoft C# extension, it would probably be better to report it in their repository (https://github.com/dotnet/vscode-csharp). Make sure to mention the version of the extension you are using, and whether or not you're also using the C# Dev Kit extension (https://github.com/microsoft/vscode-dotnettools).

**Comment by geekley** [comment]
@ana-rchy @jasonmalinowski For me on v2.8.23 of Code C# extension it's now partially working. I no longer get error squiggles on references defined in generated code. But when I try to use "jump to definition" or "find all references" where it involves generated code, I get [this bug](https://github.com/dotnet/vscode-csharp/issues/6426).
