### ISSUE TITLE
Trying to connect to Godot causes a syntax error in Powershell Core

### ISSUE THREAD

**Issue by sitiom** [godotengine/godot-csharp-vscode#8]
When I try to connect to Godot by opening it in the notif shown in the lower-left corner with Powershell Core selected as my default shell, I get this error.

![image](https://user-images.githubusercontent.com/56180050/91672008-12051e80-eb5e-11ea-808f-c07164470c7c.png)

It seems to be missing the `&` before the command as it works in Windows Powershell.

**Comment by neikeq** [comment]
The `Open Godot Editor` notification is from the [GDScript plugin](https://github.com/godotengine/godot-vscode-plugin) (this repo is only the C# plugin).
Feel free to re-open this issue there: https://github.com/godotengine/godot-vscode-plugin/issues
